"""
ECS Fargate entrypoint — runs the pipeline and handles post-processing.

Steps:
1. Run the brief generation pipeline
2. Upload artifacts to S3
3. Push brief to main branch (triggers deploy-and-notify workflow)
4. Send preview email to admin
"""

import asyncio
import json
import logging
import os
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

import boto3

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("run_pipeline")

# Environment variables (set by ECS task definition)
ARTIFACTS_BUCKET = os.environ.get("ARTIFACTS_BUCKET", "")
SES_FROM_EMAIL = os.environ.get("SES_FROM_EMAIL", "brief@idealbrief.org")
ALERT_EMAIL = os.environ.get("ALERT_EMAIL", "")
CONTENT_REPO = os.environ.get("CONTENT_REPO", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "prod")


def find_brief_dir() -> Path:
    """Find the most recently generated brief directory."""
    briefs_dir = Path("briefs")
    if not briefs_dir.exists():
        raise FileNotFoundError("No briefs directory found after pipeline run")

    dirs = sorted(
        [d for d in briefs_dir.iterdir() if d.is_dir()],
        key=lambda d: d.name,
        reverse=True,
    )

    if not dirs:
        raise FileNotFoundError("No brief subdirectories found")

    return dirs[0]


def upload_artifacts(brief_dir: Path, brief_id: str):
    """Upload brief artifacts to S3 for the email sender Lambda."""
    if not ARTIFACTS_BUCKET:
        logger.warning("ARTIFACTS_BUCKET not set, skipping S3 upload")
        return

    s3 = boto3.client("s3")
    prefix = f"briefs/{brief_id}"

    artifact_files = ["meta.json", "dossiers.json", "output.json", "brief.md"]

    for filename in artifact_files:
        filepath = brief_dir / filename
        if filepath.exists():
            key = f"{prefix}/{filename}"
            s3.upload_file(str(filepath), ARTIFACTS_BUCKET, key)
            logger.info(f"Uploaded {key}")

    # Upload email.html if it exists (generated by email template step)
    email_path = brief_dir / "email.html"
    if email_path.exists():
        s3.upload_file(str(email_path), ARTIFACTS_BUCKET, f"{prefix}/email.html")
        logger.info(f"Uploaded {prefix}/email.html")
    else:
        # Use brief.md as fallback artifact
        logger.info("No email.html found, email sender will need to render from brief.md")

    logger.info(f"Artifacts uploaded to s3://{ARTIFACTS_BUCKET}/{prefix}/")


def push_brief_to_repo(brief_dir: Path, brief_id: str) -> bool:
    """Clone content repo, add brief files, and push directly to main."""
    if not CONTENT_REPO:
        logger.warning("CONTENT_REPO not set, skipping push")
        return False

    if not GITHUB_TOKEN:
        logger.warning("GITHUB_TOKEN not set, skipping push")
        return False

    work_dir = Path("/tmp/repo")

    env = {
        **os.environ,
        "GH_TOKEN": GITHUB_TOKEN,
    }

    try:
        # Clone the repo (single-repo setup: code + content in same repo)
        subprocess.run(
            ["git", "clone", "--depth", "1",
             f"https://x-access-token:{GITHUB_TOKEN}@github.com/{CONTENT_REPO}.git",
             str(work_dir)],
            check=True, capture_output=True, text=True, env=env,
        )

        subprocess.run(
            ["git", "config", "user.email", "pipeline@idealbrief.org"],
            cwd=work_dir, check=True, capture_output=True,
        )
        subprocess.run(
            ["git", "config", "user.name", "IDEAL Brief Pipeline"],
            cwd=work_dir, check=True, capture_output=True,
        )

        # Copy brief output into _briefs/YYYY-MM-DD/ (Jekyll collection directory)
        target_dir = work_dir / "_briefs" / brief_id
        target_dir.mkdir(parents=True, exist_ok=True)

        # Copy markdown files only (exclude large JSON files not needed for rendering)
        skip_files = {"output.json", "dossiers.json"}
        for f in brief_dir.iterdir():
            if f.is_file() and f.name not in skip_files:
                subprocess.run(["cp", str(f), str(target_dir / f.name)], check=True)

        # Copy dossier markdown files
        dossier_src = brief_dir / "dossiers"
        if dossier_src.exists():
            dossier_dst = target_dir / "dossiers"
            dossier_dst.mkdir(exist_ok=True)
            for f in dossier_src.glob("*.md"):
                subprocess.run(["cp", str(f), str(dossier_dst / f.name)], check=True)

        # Stage, commit, push directly to main
        subprocess.run(
            ["git", "add", "_briefs/"],
            cwd=work_dir, check=True, capture_output=True,
        )
        subprocess.run(
            ["git", "commit", "-m", f"Brief: {brief_id}"],
            cwd=work_dir, check=True, capture_output=True, text=True,
        )
        subprocess.run(
            ["git", "push", "origin", "main"],
            cwd=work_dir, check=True, capture_output=True, text=True, env=env,
        )

        logger.info(f"Brief {brief_id} pushed to main")
        return True

    except subprocess.CalledProcessError as e:
        logger.error(f"Push to main failed: {e.stderr}")
        return False  # Non-fatal — pipeline still uploaded artifacts to S3


def send_preview_email(brief_dir: Path, brief_id: str, pushed: bool):
    """Send a preview email to the admin."""
    if not ALERT_EMAIL:
        logger.warning("ALERT_EMAIL not set, skipping preview email")
        return

    ses = boto3.client("ses")

    # Load meta
    meta_path = brief_dir / "meta.json"
    meta = {}
    if meta_path.exists():
        with open(meta_path) as f:
            meta = json.load(f)

    # Load executive summary from output.json
    exec_summary = ""
    output_path = brief_dir / "output.json"
    if output_path.exists():
        with open(output_path) as f:
            data = json.load(f)
            exec_summary = data.get("executive_summary", "")

    status = "Pushed to main — deploy in progress." if pushed else "Push to main failed — check logs."

    body = f"""IDEAL Brief pipeline completed for {brief_id}.

Leaders: {meta.get('leader_count', '?')}
Top Stories: {meta.get('main_story_count', '?')}

Executive Summary:
{exec_summary[:500]}

Status: {status}
Site: https://idealbrief.org

Artifacts uploaded to S3: s3://{ARTIFACTS_BUCKET}/briefs/{brief_id}/
"""

    try:
        ses.send_email(
            Source=SES_FROM_EMAIL,
            Destination={"ToAddresses": [ALERT_EMAIL]},
            Message={
                "Subject": {
                    "Data": f"[IDEAL Brief] Preview ready: {brief_id}",
                    "Charset": "UTF-8",
                },
                "Body": {"Text": {"Data": body, "Charset": "UTF-8"}},
            },
        )
        logger.info(f"Preview email sent to {ALERT_EMAIL}")
    except Exception as e:
        logger.error(f"Failed to send preview email: {e}")
        # Non-fatal — don't crash the pipeline for email failure


async def run():
    """Main orchestration."""
    logger.info("=" * 60)
    logger.info("IDEAL Brief Pipeline — Starting")
    logger.info(f"Environment: {ENVIRONMENT}")
    logger.info("=" * 60)

    # Step 1: Run the pipeline
    logger.info("Step 1: Running brief generation pipeline")
    from src.graph import PDBWorkflow

    workflow = PDBWorkflow(use_langgraph=False)

    end_date = datetime.utcnow().strftime("%Y-%m-%d")
    start_date = (datetime.utcnow() - timedelta(days=7)).strftime("%Y-%m-%d")

    brief = await workflow.run(
        date_range_start=start_date,
        date_range_end=end_date,
    )

    logger.info(f"Pipeline complete: {len(brief.leader_dossiers)} leaders, "
                f"{len(brief.main_stories)} top stories")

    # Step 2: Find the output directory
    brief_dir = find_brief_dir()
    brief_id = brief_dir.name  # e.g., "20260208"

    # Convert YYYYMMDD to YYYY-MM-DD for consistency
    if len(brief_id) == 8 and brief_id.isdigit():
        brief_id_formatted = f"{brief_id[:4]}-{brief_id[4:6]}-{brief_id[6:]}"
    else:
        brief_id_formatted = brief_id

    # Step 3: Upload artifacts to S3
    logger.info("Step 2: Uploading artifacts to S3")
    upload_artifacts(brief_dir, brief_id_formatted)

    # Step 4: Push brief to main
    logger.info("Step 3: Pushing brief to main")
    pushed = push_brief_to_repo(brief_dir, brief_id_formatted)

    # Step 5: Send preview email
    logger.info("Step 4: Sending preview email")
    send_preview_email(brief_dir, brief_id_formatted, pushed)

    logger.info("=" * 60)
    logger.info("Pipeline complete!")
    logger.info(f"  Brief: {brief_id_formatted}")
    logger.info(f"  Pushed to main: {pushed}")
    logger.info(f"  Artifacts: s3://{ARTIFACTS_BUCKET}/briefs/{brief_id_formatted}/")
    logger.info("=" * 60)


def main():
    try:
        asyncio.run(run())
    except Exception as e:
        logger.exception(f"Pipeline failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
